import { FX_SHOPIFY_ORG, formatMoney, type FxAppSpec } from "@nova/shared";
import type { HostedApp } from "./apps-registry";

/**
 * Build pack — the single markdown document Claude Cowork pulls to implement
 * the Shopify app end to end AND wire it into the Nova platform. Phased: a
 * "Delivery phases & gates" section sequences the work; each phase is gated and
 * never reopens an earlier phase's frozen contracts. Self-contained: app config,
 * plans/billing, the Nova integration contract, every screen spec, the backend
 * spec, the reliability bar, and a phase-gated build order. Phase E serves this
 * at GET /v1/admin/engine/apps/:id/spec/export.
 */
export function buildPackMarkdown(hosted: HostedApp, spec: FxAppSpec): string {
  const { app, engine, modules, db, origin } = hosted;
  const L: string[] = [];
  const push = (s = "") => L.push(s);

  push(`# Build pack: ${app.name}`);
  push();
  push(`> Generated by Nova Apps Platform on ${new Date().toISOString().slice(0, 10)}.`);
  push(`> Audience: Claude Cowork building this Shopify app end to end and wiring it into the Nova platform. Treat every "Acceptance" and "Gate" list as the definition of done.`);
  push();

  // ── §1 App ────────────────────────────────────────────────────
  push(`## 1. App`);
  push();
  push(`- Name: **${app.name}** — ${app.tagline}`);
  if (app.description) push(`- Description: ${app.description}`);
  push(`- Slug: \`${app.slug}\` · Status: ${app.status} · Pricing: ${app.pricingModel}`);
  push(`- Shopify org: ${FX_SHOPIFY_ORG.name} (#${FX_SHOPIFY_ORG.id}) · App ID: ${engine.shopifyAppId ?? "pending"}`);
  push(`- Repo: \`${engine.repoUrl}\` · Modules: ${modules.join(", ")}`);
  const planSummary = app.plans.length
    ? app.plans.map((p) => `${p.name} ${p.amount === 0 ? "free" : `${formatMoney(p.amount, p.currency)}/${p.interval === "ANNUAL" ? "yr" : "mo"}`}`).join(" · ")
    : "—";
  push(`- Plans: ${planSummary}`);
  push(`- Problem: ${spec.summary.problem}`);
  push(`- User: ${spec.summary.user}`);
  push(`- Outcome: ${spec.summary.outcome}`);
  push();

  // ── §2 Stack & conventions ────────────────────────────────────
  push(`## 2. Stack & conventions (non-negotiable)`);
  push();
  push(`- Scaffold: \`shopify app init\` → **React Router template** (Shopify's recommended path); Polaris web components + App Bridge for all App Home UI.`);
  push(`- Build pages from Polaris **page patterns**: templates (homepage/settings/index/detail) + compositions (setup-guide, data-table, empty-state…). Match Built for Shopify standards.`);
  push(`- Auth: **embedded app + token exchange** — App Bridge mints a ~60s session token (signed with the app secret); exchange it for an access token to call the Admin API. Managed install applies scopes from \`shopify.app.toml\`. No cookies.`);
  push(`- Backend hosted at \`${origin}\` — OAuth \`/api/auth\`, webhooks \`/api/webhooks\` (verify X-Shopify-Hmac-Sha256 with the app secret).`);
  push(`- Database: per-app Postgres via Prisma — schema at \`${db.schemaPath}\`, env \`${db.envVar}\`. Never touch other apps' DBs or the platform DB.`);
  push(`- Every shop-scoped table carries \`shopId\`; GDPR redact purges by it.`);
  push(`- OAuth scopes: ${app.scopes.length > 0 ? app.scopes.map((s) => `\`${s}\``).join(", ") : "derive from Admin GraphQL usage below"}.`);
  push();

  // section numbering (phases section is optional)
  let sec = 3;
  const phasesNo = spec.phases?.length ? sec++ : null;
  const plansNo = sec++;
  const novaNo = sec++;
  const screensNo = sec++;
  const backendNo = sec++;
  const relNo = spec.reliabilityBar?.length ? sec++ : null;
  const buildNo = sec;

  // ── §3 Delivery phases & gates ────────────────────────────────
  if (phasesNo) {
    const phases = [...spec.phases!].sort((a, b) => a.number - b.number);
    const nameOf = (key: string) => spec.screens.find((s) => s.key === key)?.name ?? key;
    push(`## ${phasesNo}. Delivery phases & gates`);
    push();
    push(`Build **phase by phase**. A phase is complete only when **every gate item is verified from the real code AND the Nova platform** — not from a checkbox alone. Do not start a phase until the previous phase's gate is fully checked and audited (operational runbook + per-phase Cowork prompts: \`encore-DELIVERY-PLAN.md\`). Phases never reopen an earlier phase's frozen contracts — that is a change-control event (\`CHANGE-CONTROL.md\`).`);
    phases.forEach((p) => {
      push();
      push(`### ${phasesNo}.${p.number} Phase ${p.number} — ${p.name}`);
      push();
      push(`- Goal: ${p.goal}`);
      push(`- Scope: ${p.scope}`);
      if (p.screens?.length) push(`- Screens: ${p.screens.map(nameOf).join(", ")} (see §${screensNo})`);
      if (p.spikes?.length) {
        push(`- Blocking spikes (resolve before exit):`);
        p.spikes.forEach((s) => push(`  - ${s}`));
      }
      push(`- Gate — phase complete when (verify from code + platform):`);
      push();
      p.gate.forEach((g) => push(`- [ ] ${g}`));
    });
    push();
  }

  // ── §N Plans & billing ────────────────────────────────────────
  push(`## ${plansNo}. Plans & billing`);
  push();
  push(`Pricing model: **${app.pricingModel}**. Sync these to the Billing API and the Nova \`AppPlan\` rows:`);
  push();
  push("| plan | price | interval | trial |");
  push("|---|---|---|---|");
  app.plans.forEach((p) =>
    push(`| ${p.name} | ${p.amount === 0 ? "Free" : formatMoney(p.amount, p.currency)} | ${p.interval === "ANNUAL" ? "annual" : "every 30 days"} | ${p.trialDays > 0 ? `${p.trialDays} days` : "—"} |`),
  );
  push();
  push(`- Create the subscription via the Billing API when the merchant selects a plan; \`app_subscriptions/update\` is forwarded to Nova ingress (the billing source of truth — see §${novaNo}).`);
  push(`- **Per-store comp / discount:** before creating the subscription, read the platform plan override for the shop (\`Installation.planOverride\`: \`FREE\` | \`PERCENT\` | \`FIXED\`) and price accordingly. A comped store is billed free/discounted, never the public price; a free comp creates no charge.`);
  push(`- Billing stops on uninstall — never charge after \`app/uninstalled\`.`);
  push();

  // ── §N Nova platform integration ──────────────────────────────
  push(`## ${novaNo}. Nova platform integration (wire this exactly)`);
  push();
  push(`This app is one tenant of the Nova Apps Platform. Two signed channels keep the platform's installs, billing, and commissions correct — without them, revenue and agency commissions never appear. \`NOVA_API\` is the platform API base URL.`);
  push();
  push(`### ${novaNo}.1 Install-confirm callback`);
  push(`After OAuth / token-exchange completes, call \`POST {NOVA_API}/v1/internal/installations/confirm\` — HMAC-signed with \`NOVA_INSTALL_CONFIRM_SECRET\`. Body: \`{ shopDomain, appSlug: "${app.slug}", planName?, installedAt }\`. This flips the Installation to ACTIVE and locks the immutable agency referral attribution.`);
  push();
  push(`### ${novaNo}.2 Webhook forwarding to ingress`);
  push(`Handle these app-locally **and** forward them (HMAC-signed with \`NOVA_INGRESS_HMAC_SECRET\`) to \`{NOVA_API}/v1/webhooks/shopify/${app.slug}\`:`);
  push(`- \`app_subscriptions/update\`, \`app/uninstalled\` — billing + lifecycle (this is how charges → commissions are derived in the platform ledger).`);
  push(`- \`customers/data_request\`, \`customers/redact\`, \`shop/redact\` — GDPR; respond **200**, return **401** on an invalid HMAC, complete within 30 days.`);
  push();
  push(`### ${novaNo}.3 Billing sync`);
  push(`- AppPlan rows (§${plansNo}) are the plan constants; Billing API mutations use them.`);
  push(`- Honor \`Installation.planOverride\` (per-store comp/discount) at subscription creation.`);
  push();
  push(`### ${novaNo}.4 Per-app database`);
  push(`Isolated Postgres via Prisma at \`${db.schemaPath}\` (env \`${db.envVar}\`) — one database + one migration history for this app only.`);
  push();

  let novaSub = 5;
  if (spec.integrations?.length) {
    push(`### ${novaNo}.${novaSub} External integrations`);
    spec.integrations.forEach((i) => {
      push(`- **${i.name}** (${i.direction ?? "outbound"}) — ${i.purpose}`);
      if (i.env?.length) push(`  - Env: ${i.env.map((e) => `\`${e}\``).join(", ")}`);
      if (i.events?.length) push(`  - Events: ${i.events.map((e) => `\`${e}\``).join(", ")}`);
    });
    push();
    novaSub += 1;
  }

  push(`### ${novaNo}.${novaSub} Environment variables`);
  push();
  push("| var | purpose |");
  push("|---|---|");
  push(`| \`SHOPIFY_API_KEY\` / \`SHOPIFY_API_SECRET\` | App client_id + secret (the secret also verifies webhook HMAC) |`);
  push(`| \`SHOPIFY_APP_URL\` | Public app URL (\`${origin}\`) |`);
  push(`| \`SCOPES\` | ${app.scopes.join(",") || "(derive from Admin GraphQL usage)"} |`);
  push(`| \`${db.envVar}\` | Per-app Postgres connection string |`);
  push(`| \`APP_ENCRYPTION_KEY\` | Encrypts offline access tokens at rest |`);
  push(`| \`NOVA_API\` | Platform API base URL |`);
  push(`| \`NOVA_INGRESS_HMAC_SECRET\` | Signs forwarded webhooks to ingress |`);
  push(`| \`NOVA_INSTALL_CONFIRM_SECRET\` | Signs the install-confirm callback |`);
  spec.integrations?.forEach((i) => i.env?.forEach((e) => push(`| \`${e}\` | ${i.name} |`)));
  push();

  // ── §N Screens (ordered by phase) ─────────────────────────────
  const phaseOfKey = (key: string) => spec.phases?.find((p) => p.screens?.includes(key))?.number;
  const orderedScreens = phasesNo
    ? spec.screens
        .map((s, idx) => ({ s, idx }))
        .sort((a, b) => (phaseOfKey(a.s.key) ?? 99) - (phaseOfKey(b.s.key) ?? 99) || a.idx - b.idx)
        .map((x) => x.s)
    : spec.screens;

  push(`## ${screensNo}. Screens (${spec.screens.length})`);
  orderedScreens.forEach((s, i) => {
    const ph = phaseOfKey(s.key);
    push();
    push(`### ${screensNo}.${i + 1} ${s.name} \`${s.status}\`${ph != null ? ` · Phase ${ph}` : ""}`);
    push();
    push(`- Surface: ${s.surface} · Template: ${s.template}`);
    push(`- ${s.surface === "app-home" ? "Route" : "Target"}: \`${s.route}\``);
    push(`- Purpose: ${s.purpose}`);
    if (s.primaryAction) push(`- Title bar primary action: ${s.primaryAction}`);
    if (s.secondaryActions?.length) push(`- Secondary actions: ${s.secondaryActions.join(" · ")}`);
    push();
    push(`Sections (in order):`);
    push();
    s.sections.forEach((sec2, j) => {
      push(`${j + 1}. **${sec2.title}** — \`${sec2.composition}\` (${sec2.components.join(", ")})`);
      push(`   - Content: ${sec2.content || "TBD"}`);
      if (sec2.data) push(`   - Data: ${sec2.data}`);
    });
    const states = [
      s.emptyState && `Empty: ${s.emptyState}`,
      s.loadingState && `Loading: ${s.loadingState}`,
      s.errorState && `Error: ${s.errorState}`,
    ].filter(Boolean);
    if (states.length) {
      push();
      push(`States: ${states.join(" · ")}`);
    }
    if (s.acceptance.length) {
      push();
      push(`Acceptance:`);
      push();
      s.acceptance.forEach((a) => push(`- [ ] ${a}`));
    }
  });

  // ── §N Backend ────────────────────────────────────────────────
  push();
  push(`## ${backendNo}. Backend`);
  push();
  push(`### ${backendNo}.1 Data model (Prisma, ${db.schemaPath})`);
  spec.backend.entities.forEach((e) => {
    push();
    push(`**${e.name}** — ${e.purpose}`);
    push();
    push("| field | type | required | note |");
    push("|---|---|---|---|");
    e.fields.forEach((f) => push(`| \`${f.name}\` | ${f.type} | ${f.required ? "yes" : "no"} | ${f.note ?? ""} |`));
    if (e.relations?.length) push(`Relations: ${e.relations.join(" · ")}`);
  });
  push();
  push(`### ${backendNo}.2 Endpoints`);
  push();
  push("| method | path | auth | purpose | reads / writes |");
  push("|---|---|---|---|---|");
  spec.backend.endpoints.forEach((e) =>
    push(`| ${e.method} | \`${e.path}\` | ${e.auth} | ${e.purpose} | ${[e.reads && `R: ${e.reads}`, e.writes && `W: ${e.writes}`].filter(Boolean).join(" · ") || "—"} |`),
  );
  push();
  push(`### ${backendNo}.3 Webhook handlers`);
  push();
  spec.backend.webhooks.forEach((w) => push(`- \`${w.topic}\` → ${w.handler}${w.writes ? ` (writes: ${w.writes})` : ""}`));
  push();
  push(`### ${backendNo}.4 Scheduled jobs`);
  push();
  if (spec.backend.jobs.length === 0) push(`- none`);
  spec.backend.jobs.forEach((j) => push(`- \`${j.name}\` (${j.schedule}) — ${j.behavior}`));
  push();
  push(`### ${backendNo}.5 Admin GraphQL usage`);
  push();
  push(spec.backend.adminApi.length > 0 ? spec.backend.adminApi.map((a) => `- ${a}`).join("\n") : "- TBD");
  push();

  // ── §N Reliability bar ────────────────────────────────────────
  if (relNo) {
    push(`## ${relNo}. Reliability bar (definition of done — "must never")`);
    push();
    push(`A version that violates any of these does not ship:`);
    push();
    spec.reliabilityBar!.forEach((r) => push(`- [ ] ${r}`));
    push();
  }

  // ── §N Build order ────────────────────────────────────────────
  push(`## ${buildNo}. Build order for Cowork`);
  push();
  if (phasesNo) {
    push(`Work **phase by phase per §${phasesNo}**. Within a phase:`);
    push();
    push(`1. Confirm the previous phase's gate (§${phasesNo}) is fully checked and audited before starting (Phase 0 has no predecessor).`);
    push(`2. Build the phase's screens (§${screensNo}) and backend (§${backendNo}) — each screen done only when its acceptance boxes check.`);
    push(`3. Keep the Nova wiring (§${novaNo}) intact; new work is additive — never alter an earlier phase's frozen contract without change control (\`CHANGE-CONTROL.md\`).`);
    push(`4. Check off the phase gate (§${phasesNo}.N), run the post-phase audit, then \`shopify app deploy\` + dev-store test.`);
    push();
    push(`First-time scaffolding (Phase 0): \`shopify app init\` (React Router) → wire \`shopify.app.toml\` (scopes, app URL \`${origin}\`, webhook subscriptions, app proxy) → implement the Prisma schema (§${backendNo}.1) + first migration against \`${db.envVar}\` → Nova wiring (§${novaNo}) → resolve the blocking spikes.`);
  } else {
    push(`1. Scaffold from the React Router template; wire \`shopify.app.toml\` (scopes, app URL \`${origin}\`, webhook subscriptions, app proxy).`);
    push(`2. Implement the Prisma schema (§${backendNo}.1) and run the first migration against \`${db.envVar}\`.`);
    push(`3. **Nova wiring (§${novaNo}):** install-confirm callback + webhook forwarding to ingress, both HMAC-signed.`);
    push(`4. Webhook receiver + handlers (§${backendNo}.3); then screens (§${screensNo}).`);
  }
  if (relNo) push(`${phasesNo ? "" : "5. "}Verify every item in the reliability bar (§${relNo}) before shipping.`);
  push();

  return L.join("\n");
}
