import { Inject, Injectable, NotFoundException } from "@nestjs/common";
import { prisma as prismaSingleton } from "@nova/database";
import { PRISMA } from "../../prisma/prisma.module";

/**
 * Spec: docs/03-modules/tool-engine.md — platform-side engine for Tools (blueprint + build-pack +
 * release tracking). Actual repo scaffolding / CI deploy runs on the Mac/CI (standalone-repo model);
 * this module stores the blueprint and exports the build-pack the dev/Cowork implements from.
 */
@Injectable()
export class ToolEngineService {
  constructor(@Inject(PRISMA) private readonly prisma: typeof prismaSingleton) {}

  private async tool(id: string) {
    const t = await this.prisma.tool.findUnique({ where: { id }, include: { plans: { orderBy: { baseAmount: "asc" } } } });
    if (!t) throw new NotFoundException(`Tool not found: ${id}`);
    return t;
  }

  async getSpec(id: string) {
    return { spec: (await this.tool(id)).spec ?? null };
  }

  async patchSpec(id: string, spec: unknown) {
    await this.assertExists(id);
    const t = await this.prisma.tool.update({ where: { id }, data: { spec: spec as object } });
    return { spec: t.spec };
  }

  async getBridge(id: string) {
    const t = await this.tool(id);
    return { usesStoreBridge: t.usesStoreBridge, requiredScopes: t.requiredScopes };
  }

  async patchBridge(id: string, dto: { usesStoreBridge?: boolean; requiredScopes?: string[] }) {
    await this.assertExists(id);
    const t = await this.prisma.tool.update({
      where: { id },
      data: {
        ...(dto.usesStoreBridge !== undefined ? { usesStoreBridge: dto.usesStoreBridge } : {}),
        ...(dto.requiredScopes ? { requiredScopes: dto.requiredScopes } : {}),
      },
    });
    return { usesStoreBridge: t.usesStoreBridge, requiredScopes: t.requiredScopes };
  }

  async getChecklist(id: string) {
    const t = await this.tool(id);
    return { checklist: t.releaseChecklist ?? this.defaultChecklist(t.usesStoreBridge) };
  }

  async patchChecklist(id: string, checklist: unknown) {
    await this.assertExists(id);
    const t = await this.prisma.tool.update({ where: { id }, data: { releaseChecklist: checklist as object } });
    return { checklist: t.releaseChecklist };
  }

  /** CI reports build/deploy state for the tool's standalone repo. */
  async ciCallback(payload: { toolSlug: string; latestVersion?: string; repoUrl?: string }) {
    const t = await this.prisma.tool.findUnique({ where: { slug: payload.toolSlug } });
    if (!t) throw new NotFoundException(`Tool not found: ${payload.toolSlug}`);
    await this.prisma.tool.update({
      where: { id: t.id },
      data: {
        ...(payload.latestVersion ? { latestVersion: payload.latestVersion } : {}),
        ...(payload.repoUrl ? { repoUrl: payload.repoUrl } : {}),
      },
    });
    return { ok: true };
  }

  /** The build-pack: one self-contained markdown doc to implement the tool repo from. */
  async exportBuildPack(id: string): Promise<string> {
    const t = await this.tool(id);
    const plans = t.plans.map((p) => `- **${p.name}** (${p.model}) — base ${p.baseAmount} ${p.currency}/${p.interval}, ${p.trialDays}d trial${p.perStore ? `, +${p.perStoreAmount ?? 0}/store` : ""}`).join("\n") || "_no plans yet_";
    const spec = t.spec ? "```json\n" + JSON.stringify(t.spec, null, 2) + "\n```" : "_blueprint not authored yet — POST the spec to `/admin/tool-engine/tools/:id/spec` first._";
    return `# ${t.name} — Nova Tool Build Pack

> Generated by tool-engine. Standalone repo + own Postgres DB; wired to the platform via the integration contract. Implement this with Cowork or a dev.

## Config
- slug: \`${t.slug}\` · type: **${t.toolType}** · status: ${t.status}
- usesStoreBridge: **${t.usesStoreBridge}**${t.usesStoreBridge ? ` · requiredScopes: ${t.requiredScopes.join(", ") || "(none set)"}` : ""}
- repo: ${t.repoUrl ?? "(create from nova-tool-template)"} · latestVersion: ${t.latestVersion ?? "—"}

## Plans (Stripe wiring is P6 — metadata for now)
${plans}

## Nova wiring (integration contract)
- **Entitlement check (I-12, mandatory):** before any gated work, call
  \`POST {NOVA_API}/v1/entitlements/${t.slug}/check\` with \`X-Nova-Signature\` (HMAC \`NOVA_ENTITLEMENT_SECRET\`), body \`{ "agencyId": "<id>" }\`; proceed only if \`access === true\`.
${t.usesStoreBridge ? "- **Store Bridge (P5):** all store reads/writes go through the Bridge GraphQL proxy — never hold raw Shopify tokens (I-13).\n" : ""}- **Usage reporting (P6):** report metered usage to \`POST {NOVA_API}/v1/tools/${t.slug}/usage\`.
- Per-tool Postgres (\`TOOL_DB_URL__${t.slug.replace(/-/g, "_").toUpperCase()}\`), own Prisma schema + migrations.

## Blueprint
${spec}

## Build order
1. Scaffold from \`nova-tool-template\` → repo + per-tool DB.
2. Implement the agency-facing UI + backend per the blueprint.
3. Add the **server-side entitlement check** at every gated action.
4. ${t.usesStoreBridge ? "Wire Store Bridge calls (P5)." : "(No store access — pure agency tool.)"}
5. Deploy (CI → \`POST /internal/tool-engine/ci-callback\`); register/grant via the Admin Tools pillar.
`;
  }

  private defaultChecklist(usesStoreBridge: boolean) {
    return [
      { key: "entitlement-checks", label: "Entitlement check at every gated action", done: false },
      ...(usesStoreBridge ? [{ key: "bridge-scopes", label: "Store Bridge requiredScopes approved (P5)", done: false }] : []),
      { key: "deploy", label: "Standalone repo deployed; CI reports version", done: false },
      { key: "smoke", label: "Granted agency can use it end-to-end", done: false },
    ];
  }

  private async assertExists(id: string) {
    const count = await this.prisma.tool.count({ where: { id } });
    if (count === 0) throw new NotFoundException(`Tool not found: ${id}`);
  }
}
